name: Check formatting

on:
  push:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  format-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone airnode
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.1'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install
      - name: Check formatting
        run: yarn run format:check
