name: Check Markdown links
on:
  push:
  pull_request:
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'no'
        config-file: .github/workflows/markdown-link-check.config.json
        folder-path: 'docs/dev, docs/airnode/pre-alpha, docs/dao-members'
